apiRules:
- exclude:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never
- exclude:
    hasAttribute:
      uid: src.MyAttribute
      ctorArguments:
        - src.MyWhen.Never
